version: '3.9'

services:
  server:
    build: .
    ports:
      - '4999:4999'
  db: 
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: 'meowththatsright'
      POSTGRES_USER: 'postgres'
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
